# Generated by Django 4.0.2 on 2024-01-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
