# Generated by Django 4.0.2 on 2024-01-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_management', '0003_remove_participant_accepted_remove_participant_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
